const { Ticket } = require('../models');

const ticketdata = [
  {
    title: 'Need an MVC for this project',
    ticket_text: 'Presentation is due soon*',
    status: true,
    user_id: 1,
    priority_id: 2,
    status_change_id: 1,
    type_id: 5,
    assigned_id: 2,
    due_date: '2022-05-15',
  },
  {
    title: 'Bug in navigation',
    ticket_text: 'Links are not working at the moment. Please fix.',
    status: false,
    user_id: 2,
    priority_id: 1,
    status_change_id: 2,
    type_id: 1,
    assigned_id: 2,
    due_date: '2022-06-04',
  },
  {
    title: 'Help with CSS',
    ticket_text: "Used bootstrap 5 and bootstrap icon. Need to make user interface nicer",
    status: true,
    user_id: 3,
    priority_id: 4,
    status_change_id: 1,
    type_id: 4,
    assigned_id: 5,
    due_date: '2022-07-03',
  },
  {
    title: 'Priority Tickets Work',
    ticket_text: "Priority routes and models are not working correctly. Need immediate fix.",
    status: true,
    user_id: 3,
    priority_id: 1,
    status_change_id: 1,
    type_id: 2,
    assigned_id: 6,
    due_date: '2022-03-04',
  },
  {
    title: 'Add Type Section',
    ticket_text: "Just like with Priority and StatusChange. A type feature section would be nice. It would incorporate whether the issue is a bug, IT, feature or other issue type.",
    status: true,
    user_id: 1,
    priority_id: 2,
    status_change_id: 1,
    type_id: 4,
    assigned_id: 7,
    due_date: '2022-01-22',
  },
  {
    title: 'Wireframe',
    ticket_text: "For this project, we need a wireframe. We'll need one to start this project off.",
    status: true,
    user_id: 2,
    priority_id: 1,
    status_change_id: 2,
    type_id: 5,
    assigned_id: 4,
    due_date: '2022-01-04',
  },
  {
    title: 'Minimal Viable Product',
    ticket_text: "Need a functional project.",
    status: true,
    user_id: 1,
    priority_id: 4,
    status_change_id: 2,
    type_id: 4,
    assigned_id: 5,
    due_date: '2022-02-22',
  },
  {
    title: 'API Routes',
    ticket_text: "Update API routes to account for added features",
    status: true,
    user_id: 1,
    priority_id: 4,
    status_change_id: 2,
    type_id: 4,
    assigned_id: 2,
    due_date: '2022-02-23',
  },
  {
    title: 'Improve UI',
    ticket_text: "Update UI so that it is more intuitive for the user",
    status: true,
    user_id: 2,
    priority_id: 3,
    status_change_id: 2,
    type_id: 4,
    assigned_id: 1,
    due_date: '2022-02-24',
  },
  {
    title: 'Fix Login Bug',
    ticket_text: "When users login, they are redirected to the wrong page",
    status: true,
    user_id: 3,
    priority_id: 4,
    status_change_id: 2,
    type_id: 4,
    assigned_id: 5,
    due_date: '2022-01-01',
  },
  {
    title: 'User Email Links',
    ticket_text: "Make it so that when user clicks on an email, they are redirected to send a message to the clicked email.",
    status: true,
    user_id: 1,
    priority_id: 3,
    status_change_id: 2,
    type_id: 1,
    assigned_id: 4,
    due_date: '2022-01-02',
  },
  {
    title: 'Update Password',
    ticket_text: "Allow user to update their account login password.",
    status: false,
    user_id: 4,
    priority_id: 4,
    status_change_id: 2,
    type_id: 4,
    assigned_id: 6,
    due_date: '2022-02-02',
  },
  {
    title: 'Improve Due Date Feature',
    ticket_text: "When the user sets a due date, they are presented with a calender to select the date",
    status: true,
    user_id: 1,
    priority_id: 4,
    status_change_id: 2,
    type_id: 4,
    assigned_id: 4,
    due_date: '2022-03-04',
  },
  {
    title: 'Apply Customer Style Specs',
    ticket_text: "The customer wants a specific color and font scheme for the site and it must be implemented.",
    status: true,
    user_id: 1,
    priority_id: 4,
    status_change_id: 2,
    type_id: 2,
    assigned_id: 3,
    due_date: '2022-01-09',
  },
  {
    title: 'Build Out New Models for New Feature',
    ticket_text: "The new feature requires a new set of models to be implemented.",
    status: true,
    user_id: 1,
    priority_id: 4,
    status_change_id: 2,
    type_id: 3,
    assigned_id: 1,
    due_date: '2022-01-08',
  },
  {
    title: 'Refactor logic for rendering tables and modals',
    ticket_text: "The structure of the logic for rendering various displays, specifically tables and modals, is difficult to follow and needs to be cleaned up.",
    status: true,
    user_id: 1,
    priority_id: 4,
    status_change_id: 2,
    type_id: 1,
    assigned_id: 1,
    due_date: '2022-01-24',
  },
  {
    title: 'Fix Icons',
    ticket_text: "The icons are too small and need to be increased in size so they are more prominant on screen.",
    status: true,
    user_id: 1,
    priority_id: 4,
    status_change_id: 2,
    type_id: 4,
    assigned_id: 2,
    due_date: '2022-01-18',
  },
];

const seedTickets = () => Ticket.bulkCreate(ticketdata);

module.exports = seedTickets;
